apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: python
        image: docker.io/samahalisaber/my-ui-library:@BUILD_NUMBER@
        ports:
        - containerPort: 8080
